apiVersion: v1
kind: Service
metadata:
  name: carrier
  namespace: {{ .Release.Namespace }}
  labels:
    app: carrier
    app.kubernetes.io/name: carrier
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: carrier
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  clusterIP: None
  selector:
    app: carrier
  ports:
  - port: 5060
    name: server
