apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: consul
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: consul
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  replicas: {{ default 1 .Values.replicas.consul }}
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
        app.kubernetes.io/name: consul
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: consul
        app.kubernetes.io/part-of: wazo-c4
        helm.sh/chart: "{{ .Chart.Name }}"
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/macvlan
        checksum/config-wazo-c4: {{ include (print $.Template.BasePath "/wazo-c4-010-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: consul
        resources:
          requests:
            cpu: 50m
            memory: 16Mi
          limits:
            cpu: 2
            memory: 2Gi
        imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
        image: {{ .Values.containers.registry }}/consul:{{ .Values.containers.consulImageTag }}

