apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: consul
    app.kubernetes.io/name: consul
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: consul
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
