apiVersion: v1
kind: Service
metadata:
  name: router-confd
  namespace: {{ .Release.Namespace }}
  labels:
    app: router-confd
    app.kubernetes.io/name: router-confd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: router-confd
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  selector:
    app: router-confd
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
