apiVersion: v1
kind: Service
metadata:
  name: rtpe
  namespace: {{ .Release.Namespace }}
  labels:
    app: rtpe
    app.kubernetes.io/name: rtpe
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rtpe
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  clusterIP: None
  selector:
    app: rtpe
  ports:
  - port: 22222
    name: server
