apiVersion: v1
kind: Service
metadata:
  name: sbc
  namespace: {{ .Release.Namespace }}
  labels:
    app: sbc
    app.kubernetes.io/name: sbc
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sbc
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  selector:
    app.kubernetes.io/name: sbc
  clusterIP: None
  ports:
  - port: 5060
    protocol: UDP
    name: sip
  - port: 5062
    protocol: UDP
    name: dmq
  - port: 8000
    name: xhttp