apiVersion: v1
kind: Service
metadata:
  name: sbc-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    app: sbc
    app.kubernetes.io/name: sbc
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sbc
    app.kubernetes.io/part-of: wazo-c4
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  selector:
    app.kubernetes.io/name: sbc
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: sip
    port: 5060
    protocol: UDP
    targetPort: 5060
    nodePort: {{ default 30060 .Values.services.sbc.service.nodePort }}
